version: '3'
services:
  app:
    build: .
    ports:
      - '8100:8080'
    volumes:
      - ./my_dictionary:/work/my_dictionary
      - ./credentials.json:/work/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/work/credentials.json
    command: >
      python -m
      uvicorn my_dictionary.main:app
      --host 0.0.0.0
      --port 8080
      --reload
